model: "ARCroco3DStereo(ARCroco3DStereoConfig(freeze='encoder', state_size=768, state_pe='2d', pos_embed='RoPE100', rgb_head=True, pose_head=True,  img_size=(224, 224), head_type='linear', output_mode='pts3d+pose', depth_mode=('exp', -inf, inf), conf_mode=('exp', 1, inf), pose_mode=('exp', -inf, inf), enc_embed_dim=1024, enc_depth=24, enc_num_heads=16, dec_embed_dim=768, dec_depth=12, dec_num_heads=12))"
pretrained: cut3r_224_linear_4.pth
load_only_encoder: False
long_context: False
fixed_length: True
resume: null
benchmark: True
num_views : 8
num_test_views : 4
n_corres_train: 0
n_corres_test: 0

train_criterion: ConfLoss(Regr3DPoseBatchList(L21, norm_mode='?avg_dis'), alpha=0.2) + RGBLoss(MSE)
test_criterion: Regr3DPose(L21, norm_mode='?avg_dis', gt_scale=True, sky_loss_value=0) + Regr3DPose_ScaleInv(L21, norm_mode='?avg_dis', gt_scale=True, sky_loss_value=0) + RGBLoss(L21)

dataset29: MVS_Synth_Multi(allow_repeat=False, split='train', ROOT="../data/custom_data/processed_mvs_synth", aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})

train_dataset: 10000 @ ${dataset29}
test_dataset: 1000 @ MVS_Synth_Multi(split='test', ROOT='../data/custom_data/processed_mvs_synth', resolution=224, num_views=${num_test_views}, seed=42, n_corres=${n_corres_test})

seed: 0
batch_size: 1
accum_iter: 2
gradient_checkpointing: False
epochs: 10
start_epoch: 0
weight_decay: 0.05
lr: 1e-6
min_lr: 1e-7
warmup_epochs: 0.5
amp: 1

num_workers: 16
world_size: 1
local-rank: -1
dist_url: 'env://'
rank: 0
gpu: 0
distributed: False
dist_backend: 'nccl'

eval_freq: 1
save_freq: 0.1
keep_freq: 1
print_freq: 10
print_img_freq: 10
num_imgs_vis: 4
save_dir: 'checkpoints'
exp_name: 'linear_gto'
task: 'cut3r'
logdir: ./${save_dir}/${exp_name}/logs
output_dir: ./${save_dir}/${exp_name}/
hydra:
  verbose: True
  run:
    dir: ./${save_dir}/${exp_name}